# Generated by Django 5.1.4 on 2024-12-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_is_done_taskstatusmodel_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatusmodel',
            name='priority',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='1'),
        ),
    ]
