# Generated by Django 5.1.4 on 2024-12-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_taskstatusmodel_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', '未着手'), ('doing', '進行中'), ('undecided', '未定')], default='todo', max_length=10),
        ),
        migrations.RemoveField(
            model_name='task',
            name='progress',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', '作業'), ('meeting', '会議・打ち合わせ'), ('go_out', '外出'), ('event', 'イベント'), ('other', 'その他')], default='work', max_length=10),
        ),
        migrations.DeleteModel(
            name='TaskStatusModel',
        ),
    ]
